import { AgentRole } from './types';

export interface DevelopmentPhase {
  id: string;
  name: string;
  description: string;
  order: number;
  tasks: DevelopmentTask[];
}

export interface DevelopmentTask {
  id: string;
  title: string;
  description: string;
  completed: boolean;
  priority: 'high' | 'medium' | 'low';
  estimatedTime?: string;
  resources?: string[]; // 관련 리소스 ID 또는 URL
}

export interface DevelopmentChecklist {
  id: string;
  role: AgentRole;
  projectName: string;
  phases: DevelopmentPhase[];
  createdAt: string;
  updatedAt: string;
  completedPhases: number;
  totalPhases: number;
}

// Role별 개발 단계 템플릿
export const ROLE_DEVELOPMENT_PHASES: Record<Exclude<AgentRole, null>, DevelopmentPhase[]> = {
  frontend: [
    {
      id: 'phase-1',
      name: '프로젝트 설정',
      description: '프로젝트 초기 설정 및 환경 구성',
      order: 1,
      tasks: [
        {
          id: 'task-1-1',
          title: '프로젝트 초기화',
          description: 'Vite/Next.js 등 프로젝트 템플릿 생성',
          completed: false,
          priority: 'high',
          estimatedTime: '30분',
        },
        {
          id: 'task-1-2',
          title: '의존성 설치',
          description: '필요한 라이브러리 및 패키지 설치',
          completed: false,
          priority: 'high',
          estimatedTime: '15분',
        },
        {
          id: 'task-1-3',
          title: '개발 환경 설정',
          description: 'ESLint, Prettier, TypeScript 설정',
          completed: false,
          priority: 'medium',
          estimatedTime: '20분',
        },
      ],
    },
    {
      id: 'phase-2',
      name: 'UI 컴포넌트 개발',
      description: '재사용 가능한 UI 컴포넌트 구축',
      order: 2,
      tasks: [
        {
          id: 'task-2-1',
          title: '디자인 시스템 구축',
          description: '컬러, 타이포그래피, 스페이싱 정의',
          completed: false,
          priority: 'high',
          estimatedTime: '1시간',
        },
        {
          id: 'task-2-2',
          title: '기본 컴포넌트 개발',
          description: 'Button, Input, Card 등 기본 컴포넌트',
          completed: false,
          priority: 'high',
          estimatedTime: '2시간',
        },
        {
          id: 'task-2-3',
          title: '복합 컴포넌트 개발',
          description: 'Form, Modal, Table 등 복합 컴포넌트',
          completed: false,
          priority: 'medium',
          estimatedTime: '3시간',
        },
      ],
    },
    {
      id: 'phase-3',
      name: '상태 관리 및 라우팅',
      description: '상태 관리 및 페이지 라우팅 설정',
      order: 3,
      tasks: [
        {
          id: 'task-3-1',
          title: '상태 관리 설정',
          description: 'Context API, Redux, Zustand 등 설정',
          completed: false,
          priority: 'high',
          estimatedTime: '1시간',
        },
        {
          id: 'task-3-2',
          title: '라우팅 구성',
          description: 'React Router 등 라우팅 설정',
          completed: false,
          priority: 'high',
          estimatedTime: '30분',
        },
        {
          id: 'task-3-3',
          title: 'API 통합',
          description: '백엔드 API 연동 및 데이터 fetching',
          completed: false,
          priority: 'high',
          estimatedTime: '2시간',
        },
      ],
    },
    {
      id: 'phase-4',
      name: '스타일링 및 반응형',
      description: '스타일링 및 반응형 디자인 적용',
      order: 4,
      tasks: [
        {
          id: 'task-4-1',
          title: '스타일링 적용',
          description: 'Tailwind CSS, Styled Components 등 적용',
          completed: false,
          priority: 'high',
          estimatedTime: '2시간',
        },
        {
          id: 'task-4-2',
          title: '반응형 디자인',
          description: '모바일, 태블릿, 데스크톱 대응',
          completed: false,
          priority: 'high',
          estimatedTime: '3시간',
        },
        {
          id: 'task-4-3',
          title: '다크모드 지원',
          description: '다크모드 테마 구현',
          completed: false,
          priority: 'low',
          estimatedTime: '1시간',
        },
      ],
    },
    {
      id: 'phase-5',
      name: '테스트 및 최적화',
      description: '테스트 작성 및 성능 최적화',
      order: 5,
      tasks: [
        {
          id: 'task-5-1',
          title: '단위 테스트 작성',
          description: 'Jest, Vitest 등으로 컴포넌트 테스트',
          completed: false,
          priority: 'medium',
          estimatedTime: '2시간',
        },
        {
          id: 'task-5-2',
          title: 'E2E 테스트',
          description: 'Playwright, Cypress 등 E2E 테스트',
          completed: false,
          priority: 'medium',
          estimatedTime: '3시간',
        },
        {
          id: 'task-5-3',
          title: '성능 최적화',
          description: '코드 스플리팅, 이미지 최적화 등',
          completed: false,
          priority: 'high',
          estimatedTime: '2시간',
        },
      ],
    },
  ],
  backend: [
    {
      id: 'phase-1',
      name: '프로젝트 설정',
      description: '백엔드 프로젝트 초기 설정',
      order: 1,
      tasks: [
        {
          id: 'task-1-1',
          title: '프로젝트 초기화',
          description: 'FastAPI, Express, Django 등 프레임워크 선택 및 설정',
          completed: false,
          priority: 'high',
          estimatedTime: '30분',
        },
        {
          id: 'task-1-2',
          title: '데이터베이스 설정',
          description: 'PostgreSQL, MongoDB 등 DB 설정',
          completed: false,
          priority: 'high',
          estimatedTime: '1시간',
        },
        {
          id: 'task-1-3',
          title: '환경 변수 설정',
          description: '.env 파일 및 환경 변수 관리',
          completed: false,
          priority: 'high',
          estimatedTime: '15분',
        },
      ],
    },
    {
      id: 'phase-2',
      name: 'API 설계 및 개발',
      description: 'RESTful API 또는 GraphQL API 개발',
      order: 2,
      tasks: [
        {
          id: 'task-2-1',
          title: 'API 스펙 정의',
          description: 'OpenAPI/Swagger 스펙 작성',
          completed: false,
          priority: 'high',
          estimatedTime: '1시간',
        },
        {
          id: 'task-2-2',
          title: '엔드포인트 개발',
          description: 'CRUD API 엔드포인트 구현',
          completed: false,
          priority: 'high',
          estimatedTime: '4시간',
        },
        {
          id: 'task-2-3',
          title: '인증/인가 구현',
          description: 'JWT, OAuth 등 인증 시스템 구현',
          completed: false,
          priority: 'high',
          estimatedTime: '2시간',
        },
      ],
    },
    {
      id: 'phase-3',
      name: '데이터베이스 모델링',
      description: '데이터베이스 스키마 설계 및 구현',
      order: 3,
      tasks: [
        {
          id: 'task-3-1',
          title: '데이터 모델 설계',
          description: 'ERD 작성 및 관계 정의',
          completed: false,
          priority: 'high',
          estimatedTime: '2시간',
        },
        {
          id: 'task-3-2',
          title: '마이그레이션 작성',
          description: '데이터베이스 마이그레이션 스크립트',
          completed: false,
          priority: 'high',
          estimatedTime: '1시간',
        },
        {
          id: 'task-3-3',
          title: '시드 데이터 생성',
          description: '개발용 초기 데이터 생성',
          completed: false,
          priority: 'low',
          estimatedTime: '30분',
        },
      ],
    },
    {
      id: 'phase-4',
      name: '비즈니스 로직 구현',
      description: '핵심 비즈니스 로직 개발',
      order: 4,
      tasks: [
        {
          id: 'task-4-1',
          title: '서비스 레이어 구현',
          description: '비즈니스 로직 서비스 함수 작성',
          completed: false,
          priority: 'high',
          estimatedTime: '4시간',
        },
        {
          id: 'task-4-2',
          title: '유효성 검증',
          description: '입력 데이터 검증 로직',
          completed: false,
          priority: 'high',
          estimatedTime: '1시간',
        },
        {
          id: 'task-4-3',
          title: '에러 처리',
          description: '에러 핸들링 및 예외 처리',
          completed: false,
          priority: 'medium',
          estimatedTime: '1시간',
        },
      ],
    },
    {
      id: 'phase-5',
      name: '테스트 및 배포',
      description: '테스트 작성 및 배포 준비',
      order: 5,
      tasks: [
        {
          id: 'task-5-1',
          title: '단위 테스트',
          description: '서비스 로직 단위 테스트',
          completed: false,
          priority: 'medium',
          estimatedTime: '3시간',
        },
        {
          id: 'task-5-2',
          title: '통합 테스트',
          description: 'API 통합 테스트 작성',
          completed: false,
          priority: 'medium',
          estimatedTime: '2시간',
        },
        {
          id: 'task-5-3',
          title: '배포 설정',
          description: 'Docker, CI/CD 파이프라인 설정',
          completed: false,
          priority: 'high',
          estimatedTime: '2시간',
        },
      ],
    },
  ],
  pm: [
    {
      id: 'phase-1',
      name: '프로젝트 기획',
      description: '프로젝트 목표 및 범위 정의',
      order: 1,
      tasks: [
        {
          id: 'task-1-1',
          title: '프로젝트 목표 정의',
          description: '비즈니스 목표 및 성공 지표 정의',
          completed: false,
          priority: 'high',
          estimatedTime: '2시간',
        },
        {
          id: 'task-1-2',
          title: '요구사항 수집',
          description: '스테이크홀더 인터뷰 및 요구사항 정리',
          completed: false,
          priority: 'high',
          estimatedTime: '4시간',
        },
        {
          id: 'task-1-3',
          title: '프로젝트 범위 정의',
          description: 'MVP 범위 및 우선순위 결정',
          completed: false,
          priority: 'high',
          estimatedTime: '2시간',
        },
      ],
    },
    {
      id: 'phase-2',
      name: '사양 문서 작성',
      description: '상세 사양 문서 및 와이어프레임 작성',
      order: 2,
      tasks: [
        {
          id: 'task-2-1',
          title: '사용자 스토리 작성',
          description: 'User Story 및 Acceptance Criteria 작성',
          completed: false,
          priority: 'high',
          estimatedTime: '3시간',
        },
        {
          id: 'task-2-2',
          title: '와이어프레임 작성',
          description: 'Figma, Sketch 등으로 와이어프레임',
          completed: false,
          priority: 'high',
          estimatedTime: '4시간',
        },
        {
          id: 'task-2-3',
          title: 'API 스펙 정의',
          description: '백엔드 API 스펙 문서화',
          completed: false,
          priority: 'medium',
          estimatedTime: '2시간',
        },
      ],
    },
    {
      id: 'phase-3',
      name: '프로젝트 관리',
      description: '일정 관리 및 리스크 관리',
      order: 3,
      tasks: [
        {
          id: 'task-3-1',
          title: '일정 계획 수립',
          description: '마일스톤 및 스프린트 계획',
          completed: false,
          priority: 'high',
          estimatedTime: '2시간',
        },
        {
          id: 'task-3-2',
          title: '리스크 관리',
          description: '리스크 식별 및 대응 계획',
          completed: false,
          priority: 'medium',
          estimatedTime: '1시간',
        },
        {
          id: 'task-3-3',
          title: '리소스 할당',
          description: '팀원 역할 및 책임 정의',
          completed: false,
          priority: 'high',
          estimatedTime: '1시간',
        },
      ],
    },
    {
      id: 'phase-4',
      name: '진행 상황 관리',
      description: '일일 스탠드업 및 진행 상황 추적',
      order: 4,
      tasks: [
        {
          id: 'task-4-1',
          title: '일일 스탠드업',
          description: '팀원과 일일 진행 상황 공유',
          completed: false,
          priority: 'high',
          estimatedTime: '30분',
        },
        {
          id: 'task-4-2',
          title: '진행 상황 추적',
          description: '칸반 보드, 버너다운 차트 관리',
          completed: false,
          priority: 'high',
          estimatedTime: '1시간',
        },
        {
          id: 'task-4-3',
          title: '블로커 해결',
          description: '팀원의 블로커 식별 및 해결 지원',
          completed: false,
          priority: 'high',
          estimatedTime: '1시간',
        },
      ],
    },
    {
      id: 'phase-5',
      name: '품질 관리 및 배포',
      description: 'QA 및 배포 관리',
      order: 5,
      tasks: [
        {
          id: 'task-5-1',
          title: 'QA 계획 수립',
          description: '테스트 계획 및 시나리오 작성',
          completed: false,
          priority: 'high',
          estimatedTime: '2시간',
        },
        {
          id: 'task-5-2',
          title: '배포 계획',
          description: '스테이징, 프로덕션 배포 계획',
          completed: false,
          priority: 'high',
          estimatedTime: '1시간',
        },
        {
          id: 'task-5-3',
          title: '사용자 피드백 수집',
          description: '베타 테스트 및 피드백 수집',
          completed: false,
          priority: 'medium',
          estimatedTime: '2시간',
        },
      ],
    },
  ],
  fullstack: [
    {
      id: 'phase-1',
      name: '프로젝트 설정',
      description: '전체 스택 프로젝트 초기 설정',
      order: 1,
      tasks: [
        {
          id: 'task-1-1',
          title: '프로젝트 구조 설계',
          description: 'Monorepo 또는 분리된 레포지토리 구조 결정',
          completed: false,
          priority: 'high',
          estimatedTime: '1시간',
        },
        {
          id: 'task-1-2',
          title: '프론트엔드 설정',
          description: 'React/Vue 등 프론트엔드 프레임워크 설정',
          completed: false,
          priority: 'high',
          estimatedTime: '1시간',
        },
        {
          id: 'task-1-3',
          title: '백엔드 설정',
          description: 'Node.js/Python 등 백엔드 프레임워크 설정',
          completed: false,
          priority: 'high',
          estimatedTime: '1시간',
        },
      ],
    },
    {
      id: 'phase-2',
      name: '데이터베이스 및 API',
      description: '데이터베이스 설계 및 API 개발',
      order: 2,
      tasks: [
        {
          id: 'task-2-1',
          title: '데이터베이스 설계',
          description: '스키마 설계 및 마이그레이션',
          completed: false,
          priority: 'high',
          estimatedTime: '2시간',
        },
        {
          id: 'task-2-2',
          title: 'REST API 개발',
          description: '백엔드 API 엔드포인트 구현',
          completed: false,
          priority: 'high',
          estimatedTime: '4시간',
        },
        {
          id: 'task-2-3',
          title: 'API 클라이언트 생성',
          description: '프론트엔드 API 클라이언트 설정',
          completed: false,
          priority: 'high',
          estimatedTime: '1시간',
        },
      ],
    },
    {
      id: 'phase-3',
      name: '프론트엔드 개발',
      description: 'UI 컴포넌트 및 페이지 개발',
      order: 3,
      tasks: [
        {
          id: 'task-3-1',
          title: '컴포넌트 개발',
          description: '재사용 가능한 UI 컴포넌트 구축',
          completed: false,
          priority: 'high',
          estimatedTime: '3시간',
        },
        {
          id: 'task-3-2',
          title: '페이지 개발',
          description: '라우팅 및 페이지 컴포넌트',
          completed: false,
          priority: 'high',
          estimatedTime: '4시간',
        },
        {
          id: 'task-3-3',
          title: '상태 관리',
          description: '전역 상태 관리 설정',
          completed: false,
          priority: 'medium',
          estimatedTime: '2시간',
        },
      ],
    },
    {
      id: 'phase-4',
      name: '통합 및 인증',
      description: '프론트엔드-백엔드 통합 및 인증',
      order: 4,
      tasks: [
        {
          id: 'task-4-1',
          title: '인증 시스템 구현',
          description: 'JWT 기반 인증 구현',
          completed: false,
          priority: 'high',
          estimatedTime: '3시간',
        },
        {
          id: 'task-4-2',
          title: 'API 통합',
          description: '프론트엔드-백엔드 API 연동',
          completed: false,
          priority: 'high',
          estimatedTime: '2시간',
        },
        {
          id: 'task-4-3',
          title: '에러 처리',
          description: '전체 스택 에러 핸들링',
          completed: false,
          priority: 'medium',
          estimatedTime: '1시간',
        },
      ],
    },
    {
      id: 'phase-5',
      name: '테스트 및 배포',
      description: '전체 스택 테스트 및 배포',
      order: 5,
      tasks: [
        {
          id: 'task-5-1',
          title: '통합 테스트',
          description: '프론트엔드-백엔드 통합 테스트',
          completed: false,
          priority: 'medium',
          estimatedTime: '3시간',
        },
        {
          id: 'task-5-2',
          title: 'E2E 테스트',
          description: '전체 플로우 E2E 테스트',
          completed: false,
          priority: 'medium',
          estimatedTime: '2시간',
        },
        {
          id: 'task-5-3',
          title: '배포 설정',
          description: '프론트엔드/백엔드 배포 파이프라인',
          completed: false,
          priority: 'high',
          estimatedTime: '3시간',
        },
      ],
    },
  ],
  devops: [
    {
      id: 'phase-1',
      name: '인프라 설계',
      description: '클라우드 인프라 아키텍처 설계',
      order: 1,
      tasks: [
        {
          id: 'task-1-1',
          title: '인프라 아키텍처 설계',
          description: 'AWS/Azure/GCP 인프라 설계',
          completed: false,
          priority: 'high',
          estimatedTime: '3시간',
        },
        {
          id: 'task-1-2',
          title: '네트워크 구성',
          description: 'VPC, 서브넷, 보안 그룹 설정',
          completed: false,
          priority: 'high',
          estimatedTime: '2시간',
        },
        {
          id: 'task-1-3',
          title: '모니터링 계획',
          description: '로깅 및 모니터링 전략 수립',
          completed: false,
          priority: 'medium',
          estimatedTime: '1시간',
        },
      ],
    },
    {
      id: 'phase-2',
      name: 'CI/CD 파이프라인',
      description: '지속적 통합 및 배포 파이프라인 구축',
      order: 2,
      tasks: [
        {
          id: 'task-2-1',
          title: 'CI 파이프라인 설정',
          description: 'GitHub Actions, GitLab CI 등 설정',
          completed: false,
          priority: 'high',
          estimatedTime: '2시간',
        },
        {
          id: 'task-2-2',
          title: 'CD 파이프라인 설정',
          description: '자동 배포 파이프라인 구축',
          completed: false,
          priority: 'high',
          estimatedTime: '3시간',
        },
        {
          id: 'task-2-3',
          title: '테스트 자동화',
          description: 'CI 파이프라인에 테스트 통합',
          completed: false,
          priority: 'high',
          estimatedTime: '1시간',
        },
      ],
    },
    {
      id: 'phase-3',
      name: '컨테이너화',
      description: 'Docker 및 Kubernetes 설정',
      order: 3,
      tasks: [
        {
          id: 'task-3-1',
          title: 'Docker 이미지 빌드',
          description: '애플리케이션 Dockerfile 작성',
          completed: false,
          priority: 'high',
          estimatedTime: '2시간',
        },
        {
          id: 'task-3-2',
          title: 'Kubernetes 배포',
          description: 'K8s 매니페스트 작성 및 배포',
          completed: false,
          priority: 'high',
          estimatedTime: '3시간',
        },
        {
          id: 'task-3-3',
          title: '서비스 메시 설정',
          description: 'Istio, Linkerd 등 서비스 메시 (선택)',
          completed: false,
          priority: 'low',
          estimatedTime: '2시간',
        },
      ],
    },
    {
      id: 'phase-4',
      name: '보안 및 모니터링',
      description: '보안 설정 및 모니터링 시스템 구축',
      order: 4,
      tasks: [
        {
          id: 'task-4-1',
          title: '보안 설정',
          description: 'Secrets 관리, RBAC 설정',
          completed: false,
          priority: 'high',
          estimatedTime: '2시간',
        },
        {
          id: 'task-4-2',
          title: '로깅 시스템',
          description: 'ELK, Loki 등 로깅 시스템 구축',
          completed: false,
          priority: 'high',
          estimatedTime: '3시간',
        },
        {
          id: 'task-4-3',
          title: '모니터링 대시보드',
          description: 'Prometheus, Grafana 등 모니터링',
          completed: false,
          priority: 'high',
          estimatedTime: '2시간',
        },
      ],
    },
    {
      id: 'phase-5',
      name: '최적화 및 스케일링',
      description: '성능 최적화 및 자동 스케일링',
      order: 5,
      tasks: [
        {
          id: 'task-5-1',
          title: '성능 최적화',
          description: '리소스 사용량 최적화',
          completed: false,
          priority: 'medium',
          estimatedTime: '2시간',
        },
        {
          id: 'task-5-2',
          title: '자동 스케일링',
          description: 'HPA, VPA 등 자동 스케일링 설정',
          completed: false,
          priority: 'medium',
          estimatedTime: '2시간',
        },
        {
          id: 'task-5-3',
          title: '재해 복구 계획',
          description: '백업 및 재해 복구 전략',
          completed: false,
          priority: 'high',
          estimatedTime: '2시간',
        },
      ],
    },
  ],
  designer: [
    {
      id: 'phase-1',
      name: '디자인 리서치',
      description: '사용자 리서치 및 경쟁사 분석',
      order: 1,
      tasks: [
        {
          id: 'task-1-1',
          title: '사용자 리서치',
          description: '사용자 인터뷰 및 페르소나 정의',
          completed: false,
          priority: 'high',
          estimatedTime: '4시간',
        },
        {
          id: 'task-1-2',
          title: '경쟁사 분석',
          description: '유사 서비스 UX/UI 분석',
          completed: false,
          priority: 'high',
          estimatedTime: '3시간',
        },
        {
          id: 'task-1-3',
          title: '디자인 트렌드 조사',
          description: '최신 디자인 트렌드 및 패턴 조사',
          completed: false,
          priority: 'medium',
          estimatedTime: '2시간',
        },
      ],
    },
    {
      id: 'phase-2',
      name: '디자인 시스템 구축',
      description: '컬러, 타이포그래피, 컴포넌트 라이브러리',
      order: 2,
      tasks: [
        {
          id: 'task-2-1',
          title: '컬러 시스템 정의',
          description: 'Primary, Secondary 컬러 팔레트 정의',
          completed: false,
          priority: 'high',
          estimatedTime: '2시간',
        },
        {
          id: 'task-2-2',
          title: '타이포그래피 시스템',
          description: '폰트 스케일 및 타이포그래피 규칙',
          completed: false,
          priority: 'high',
          estimatedTime: '1시간',
        },
        {
          id: 'task-2-3',
          title: '컴포넌트 라이브러리',
          description: 'Figma 컴포넌트 라이브러리 구축',
          completed: false,
          priority: 'high',
          estimatedTime: '4시간',
        },
      ],
    },
    {
      id: 'phase-3',
      name: '와이어프레임 및 프로토타입',
      description: '로우/하이 피델리티 프로토타입',
      order: 3,
      tasks: [
        {
          id: 'task-3-1',
          title: '와이어프레임 작성',
          description: 'Figma/Sketch로 와이어프레임',
          completed: false,
          priority: 'high',
          estimatedTime: '4시간',
        },
        {
          id: 'task-3-2',
          title: '하이 피델리티 디자인',
          description: '상세 UI 디자인 완성',
          completed: false,
          priority: 'high',
          estimatedTime: '8시간',
        },
        {
          id: 'task-3-3',
          title: '인터랙티브 프로토타입',
          description: 'Figma Prototype 등 인터랙션 추가',
          completed: false,
          priority: 'medium',
          estimatedTime: '3시간',
        },
      ],
    },
    {
      id: 'phase-4',
      name: '사용자 테스트',
      description: '프로토타입 사용자 테스트',
      order: 4,
      tasks: [
        {
          id: 'task-4-1',
          title: '테스트 계획 수립',
          description: '사용자 테스트 시나리오 작성',
          completed: false,
          priority: 'high',
          estimatedTime: '1시간',
        },
        {
          id: 'task-4-2',
          title: '사용자 테스트 진행',
          description: '프로토타입으로 사용자 테스트',
          completed: false,
          priority: 'high',
          estimatedTime: '4시간',
        },
        {
          id: 'task-4-3',
          title: '피드백 반영',
          description: '사용자 피드백 분석 및 디자인 수정',
          completed: false,
          priority: 'high',
          estimatedTime: '3시간',
        },
      ],
    },
    {
      id: 'phase-5',
      name: '디자인 핸드오프',
      description: '개발팀에 디자인 전달',
      order: 5,
      tasks: [
        {
          id: 'task-5-1',
          title: '디자인 스펙 문서화',
          description: '컴포넌트 스펙 및 스타일 가이드 작성',
          completed: false,
          priority: 'high',
          estimatedTime: '3시간',
        },
        {
          id: 'task-5-2',
          title: '개발팀 브리핑',
          description: '디자인 의도 및 구현 가이드 공유',
          completed: false,
          priority: 'high',
          estimatedTime: '1시간',
        },
        {
          id: 'task-5-3',
          title: 'QA 지원',
          description: '개발된 UI 검수 및 피드백',
          completed: false,
          priority: 'medium',
          estimatedTime: '2시간',
        },
      ],
    },
  ],
};

